#+title: SciMapAi
Exploring scientific texts and concepts through interactive knowledge graphs generated by AI, powered by the LangChain python library and built using the Streamlit python library. You can check it out at https://scimapai.streamlit.app.

* Installation
Install the necessary python packages and dependencies using the environment.yml file.

#+begin_src bash
conda env create -f environment.yml
#+end_src

Once the packages have been installed and the environment is activated, run the streamlit app in your browser.
#+begin_src bash
streamlit run scimapai.py
#+end_src

* OpenAI API Key
You will be prompted to input your OpenAI API key, which will be cached as long as the app is running. A more effcient and secure approach would be to define your API key as an environment variable and export it. More information for Windows/MacOS/Linux can be found [[https://www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html][here]].

* Future Ideas
- Add description tooltips for nodes as well.
- Generate knowledge graphs in as outline of running chat conversation. Include RAG chat on science papers.
- Multi-pdf RAG with papers/lectures (https://medium.com/@baptisteloquette.entr/langchain-arxiv-tutor-long-text-summarization-retrievalqa-and-vector-databases-6d5cb1dc7e14)
- Improve the graph generation prompting to make more cohesive/less fragmented graphs. (eg. https://towardsdatascience.com/how-to-convert-any-text-into-a-graph-of-concepts-110844f22a1a)
